package com.phoenixdarts.toss.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MatchFormatSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchFormatSetAllPropertiesEquals(MatchFormatSet expected, MatchFormatSet actual) {
        assertMatchFormatSetAutoGeneratedPropertiesEquals(expected, actual);
        assertMatchFormatSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchFormatSetAllUpdatablePropertiesEquals(MatchFormatSet expected, MatchFormatSet actual) {
        assertMatchFormatSetUpdatableFieldsEquals(expected, actual);
        assertMatchFormatSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchFormatSetAutoGeneratedPropertiesEquals(MatchFormatSet expected, MatchFormatSet actual) {
        assertThat(expected)
            .as("Verify MatchFormatSet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchFormatSetUpdatableFieldsEquals(MatchFormatSet expected, MatchFormatSet actual) {
        assertThat(expected)
            .as("Verify MatchFormatSet relevant properties")
            .satisfies(e -> assertThat(e.getPoint()).as("check point").isEqualTo(actual.getPoint()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatchFormatSetUpdatableRelationshipsEquals(MatchFormatSet expected, MatchFormatSet actual) {
        assertThat(expected)
            .as("Verify MatchFormatSet relationships")
            .satisfies(e -> assertThat(e.getMatchFormat()).as("check matchFormat").isEqualTo(actual.getMatchFormat()));
    }
}
